name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Please select the command'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Init and Validate
        run: |
          cd src/terraform_folder
          terraform init
          terraform validate

      - name: Terraform Plan
        run: |
          cd src/terraform_folder
          terraform plan -no-color -out=tfplan

      - name: Terraform Action
        run: |
          cd src/terraform_folder
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve tfplan
            # echo "::set-output name=EC2_IP_ADDRESS::$(terraform output public_ip)"
          elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified."
            exit 1
          fi

      - name: Set output
        run: echo "{ec2_ip_address}={aws_instance.webserver.public_ip}">> $GITHUB_ENV
        # if: ${{ success() }}
        # run: echo "EC2_IP_ADDRESS=${{ steps.terraform.outputs.EC2_IP_ADDRESS }}" >> $GITHUB_ENV
